"""
Generate a 301 redirect map from the existing live-site crawl.

Reads crawl/mymechanicqld/summary.json (the URLs that exist today on
mymechanicqld.com.au) and cross-references against the new Next.js routes,
then outputs:
  - redirects.json     consumed by next.config.mjs at build time
  - docs/REDIRECT_MAP.md   human-readable review document

Run before launch and after any new page is added on the new site.
"""
import json
import os
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).parent
CRAWL = ROOT / 'crawl' / 'mymechanicqld' / 'summary.json'
OUT_JSON = ROOT / 'redirects.json'
OUT_MD = ROOT / 'docs' / 'REDIRECT_MAP.md'

# Pages we have built on the new Next.js site. Keep in sync with app/ routes.
# Source paths are without trailing slash; Next.js handles trailing slashes
# automatically via trailingSlash: true in next.config.mjs.
KNOWN_PAGES = {
    '/',
    '/services',
    '/areas',
    '/about',
    '/contact',
    '/faq',
    '/book',
    '/privacy-policy',
    '/terms-conditions',
    '/pricing',
    '/warranty',
    '/how-it-works',
    '/blog',
    # Services (must match content/services/)
    '/brake-repairs',
    '/starter-alternator',
    '/radiator-cooling-system',
    '/logbook-servicing',
    '/pre-purchase-inspection',
    '/battery-replacement',
    '/car-diagnostics',
    '/steering-suspension',
}

# Specific one-off mappings (case-sensitive).
SPECIFIC_REDIRECTS = {
    # The Wix preview/draft of the homepage
    '/home-old': '/',
    # Blog post that lived at a flat URL on the live site now nests under /blog/
    '/does-a-mobile-logbook-service-void-your-new-car-warranty':
        '/blog/does-a-mobile-logbook-service-void-your-new-car-warranty',
}

# Region landing pages. Until we build dedicated region pages, send these to /areas/.
REGION_URLS = {
    '/brisbane',
    '/logan',
    '/ipswich',
    '/gold-coast',
}


def normalise(url: str) -> str:
    """Drop the domain, trailing slash, query, fragment. Return path only."""
    parsed = urllib.parse.urlparse(url)
    path = parsed.path.rstrip('/')
    return path or '/'


def main() -> None:
    with open(CRAWL) as f:
        pages = json.load(f)

    crawled_paths = sorted({normalise(p['url']) for p in pages})

    redirects = []
    notes = []

    for path in crawled_paths:
        if path == '/':
            continue  # homepage stays put

        # Case-sensitive exact match (catches the /Wynnum capital-W typo too)
        if path in SPECIFIC_REDIRECTS:
            redirects.append({
                'source': path,
                'destination': SPECIFIC_REDIRECTS[path],
                'permanent': True,
            })
            notes.append((path, SPECIFIC_REDIRECTS[path], 'Specific mapping'))
            continue

        if path in REGION_URLS:
            redirects.append({
                'source': path,
                'destination': '/areas/',
                'permanent': True,
            })
            notes.append((path, '/areas/', 'Region page (interim → /areas/)'))
            continue

        # Lowercase comparison for case-mismatch URLs like /Wynnum
        path_lower = path.lower()
        if path_lower in KNOWN_PAGES:
            if path_lower != path:
                # /Wynnum → /wynnum/ — but /wynnum doesn't exist either, so
                # /areas/ is the right fallback
                redirects.append({
                    'source': path,
                    'destination': '/areas/',
                    'permanent': True,
                })
                notes.append((path, '/areas/', 'Case-mismatch typo → /areas/'))
                continue
            notes.append((path, path, 'Preserved (no redirect)'))
            continue

        if path in KNOWN_PAGES:
            notes.append((path, path, 'Preserved (no redirect)'))
            continue

        # Anything else is a suburb landing page (or unexpected). Send to /areas/.
        redirects.append({
            'source': path,
            'destination': '/areas/',
            'permanent': True,
        })
        notes.append((path, '/areas/', 'Suburb page (interim → /areas/)'))

    OUT_JSON.write_text(json.dumps(redirects, indent=2) + '\n')

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    preserved = sum(1 for n in notes if n[2] == 'Preserved (no redirect)')
    with OUT_MD.open('w') as f:
        f.write("# Redirect map: live site → new site\n\n")
        f.write(
            "Generated by `generate_redirects.py` from the live-site crawl. "
            "Re-run after every change to the new Next.js routes.\n\n"
        )
        f.write(f"- **Live URLs scanned:** {len(crawled_paths)}\n")
        f.write(f"- **Preserved** (same URL, no redirect needed): {preserved}\n")
        f.write(f"- **Redirected** (301 to a new URL): {len(redirects)}\n\n")
        f.write("## How this is wired in\n\n")
        f.write(
            "`generate_redirects.py` writes `redirects.json` at the repo root. "
            "`next.config.mjs` reads that JSON at build time and registers the "
            "redirects in Vercel's edge layer. Every redirect is a 301 (permanent).\n\n"
        )
        f.write("## Pre-launch verification\n\n")
        f.write(
            "Before launch, every old URL in this table must either resolve "
            "(preserved) or 301 to a real page (redirected). Test the top 20 "
            "old URLs (use GSC data to find the top-trafficked ones) manually.\n\n"
        )
        f.write("## Full table\n\n")
        f.write("| Live URL | Destination | Status |\n")
        f.write("|---|---|---|\n")
        for old, new, status in sorted(notes):
            if status == 'Preserved (no redirect)':
                f.write(f"| `{old}` | (same) | Preserved |\n")
            else:
                f.write(f"| `{old}` | `{new}` | 301 — {status} |\n")
        f.write("\n## Future work\n\n")
        f.write(
            "Several redirects currently funnel into `/areas/` as an interim. "
            "When we build dedicated suburb pages (Stage 5 programmatic SEO), "
            "update this script's `KNOWN_PAGES` set and re-run to remove the "
            "interim redirects.\n"
        )

    print(f"Generated {len(redirects)} redirects "
          f"({preserved} URLs preserved without redirect).")
    print(f"  JSON:     {OUT_JSON}")
    print(f"  Markdown: {OUT_MD}")


if __name__ == '__main__':
    main()
