import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Load the 301 redirect map generated by `generate_redirects.py`. If the file
// is missing, we still build cleanly; the redirects just won't be applied.
let redirectsConfig = []
try {
  const raw = readFileSync(join(__dirname, 'redirects.json'), 'utf8')
  redirectsConfig = JSON.parse(raw)
} catch (e) {
  console.warn('[next.config] redirects.json not found, no redirects loaded.')
}

// Security headers applied to every response.
// HSTS is set for two years; the preload directive only matters if/when the
// domain is submitted to https://hstspreload.org/.
const securityHeaders = [
  { key: 'X-DNS-Prefetch-Control', value: 'on' },
  { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(self), interest-cohort=()' },
]

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Match the existing mymechanicqld.com.au URL structure (trailing slashes)
  // so SEO equity carries through after migration.
  trailingSlash: true,
  poweredByHeader: false,
  images: {
    formats: ['image/avif', 'image/webp'],
    minimumCacheTTL: 60 * 60 * 24 * 7,
  },
  experimental: {
    typedRoutes: false,
  },

  async redirects() {
    return redirectsConfig
  },

  async headers() {
    return [
      {
        source: '/:path*',
        headers: securityHeaders,
      },
      {
        // Cache static images aggressively (Next.js handles the rest)
        source: '/images/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable',
          },
        ],
      },
    ]
  },
}

export default nextConfig
